approve:
- commandHelpLink: ""
  repos:
  - openshift-priv/cluster-api-provider-kubevirt
  require_self_approval: false
lgtm:
- repos:
  - openshift-priv/cluster-api-provider-kubevirt
  review_acts_as_lgtm: true
