base_images:
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: "4.13"
    namespace: ocp
    tag: hypershift-operator
  hypershift-tests:
    name: "4.12"
    namespace: ocp
    tag: hypershift-tests
  upi-installer:
    name: "4.12"
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.12"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.12"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn
  cron: 47 12 15 * *
  steps:
    cluster_profile: hypershift
    workflow: hypershift-aws-e2e-metrics
- as: e2e-aws-ovn-conformance-serial
  cron: 8 1 27 * *
  steps:
    cluster_profile: hypershift
    env:
      TEST_SUITE: openshift/conformance/serial
    workflow: hypershift-aws-conformance
- as: e2e-aws-ovn-conformance
  cron: 20 18 9 * *
  steps:
    cluster_profile: hypershift
    workflow: hypershift-aws-conformance
- as: e2e-aws-ovn-proxy-conformance
  cron: 0 14 8 * *
  steps:
    cluster_profile: hypershift
    workflow: hypershift-aws-conformance-proxy
- as: e2e-powervs
  cron: 17 16 19 * *
  steps:
    cluster_profile: hypershift-powervs
    workflow: hypershift-powervs-e2e
- as: e2e-ibmcloud-iks
  cron: 8 2 28 * *
  steps:
    env:
      BOM_VERSION: 4.10.26_openshift
      MANAGED_CLUSTER_TYPE: iks
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/iks.kubeconfig
      TEST_TYPE: main
      VERIFY_COMPLIANCE_OPERATOR_SCAN: "false"
    workflow: hypershift-ibmcloud-e2e
- as: e2e-ibmcloud-roks
  cron: 49 6 11 * *
  steps:
    env:
      BOM_VERSION: 4.11.0_openshift
      MANAGED_CLUSTER_TYPE: openshift
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/roks.kubeconfig
      TEST_TYPE: main
      VERIFY_COMPLIANCE_OPERATOR_SCAN: "true"
    workflow: hypershift-ibmcloud-e2e
zz_generated_metadata:
  branch: release-4.12
  org: openshift
  repo: hypershift
  variant: periodics
