base_images:
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: '4.13'
    namespace: ocp
    tag: hypershift-operator
  hypershift-tests:
    name: '4.12'
    namespace: ocp
    tag: hypershift-tests
  upi-installer:
    name: '4.12'
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: '4.12'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.12'
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: '4.12'
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn
  steps:
    workflow: hypershift-aws-e2e-metrics
  cron: 51 23 */9,22 * *
- as: e2e-aws-ovn-conformance-serial
  steps:
    env:
      TEST_SUITE: openshift/conformance/serial
    workflow: hypershift-aws-conformance
  cron: 36 10 */12,23 * *
- as: e2e-aws-ovn-conformance
  steps:
    workflow: hypershift-aws-conformance
  cron: 31 16 */3,12 * *
- as: e2e-aws-ovn-proxy-conformance
  steps:
    cluster_profile: aws
    workflow: hypershift-aws-conformance-proxy
  cron: 3 21 */8,22 * *
- as: e2e-powervs
  steps:
    workflow: hypershift-powervs-e2e
  cron: 38 18 */14,25 * *
- as: e2e-ibmcloud-iks
  steps:
    env:
      BOM_VERSION: 4.10.26_openshift
      MANAGED_CLUSTER_TYPE: iks
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/iks.kubeconfig
      TEST_TYPE: main
      VERIFY_COMPLIANCE_OPERATOR_SCAN: 'false'
    workflow: hypershift-ibmcloud-e2e
  cron: 0 8 */10,24 * *
- as: e2e-ibmcloud-roks
  steps:
    env:
      BOM_VERSION: 4.11.0_openshift
      MANAGED_CLUSTER_TYPE: openshift
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/roks.kubeconfig
      TEST_TYPE: main
      VERIFY_COMPLIANCE_OPERATOR_SCAN: 'true'
    workflow: hypershift-ibmcloud-e2e
  cron: 0 18 */8,20 * *
- as: e2e-aws-ovn-mce-conformance
  steps:
    cluster_profile: aws
    workflow: hypershift-mce-aws-conformance
  cron: 52 14 */8,18 * *
- as: e2e-kubevirt-conformance
  steps:
    cluster_profile: aws
    env:
      CNV_PRERELEASE_VERSION: '4.12'
    workflow: hypershift-kubevirt-conformance
  cron: 22 1 */7,16 * *
- as: e2e-kubevirt-mce-conformance
  steps:
    cluster_profile: aws
    env:
      CNV_PRERELEASE_VERSION: '4.12'
    workflow: hypershift-mce-kubevirt-conformance
  cron: 1 4 */6,15 * *
zz_generated_metadata:
  branch: release-4.12
  org: openshift
  repo: hypershift
  variant: periodics
