base_images:
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: "4.13"
    namespace: ocp
    tag: hypershift-operator
  hypershift-tests:
    name: "4.12"
    namespace: ocp
    tag: hypershift-tests
  upi-installer:
    name: "4.12"
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.12"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.12"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn
  cron: 37 15 */5,16 * *
  steps:
    workflow: hypershift-aws-e2e-metrics
- as: e2e-aws-ovn-conformance-serial
  cron: 50 11 */7,20 * *
  steps:
    env:
      TEST_SUITE: openshift/conformance/serial
    workflow: hypershift-aws-conformance
- as: e2e-aws-ovn-conformance
  cron: 31 3 */3,15 * *
  steps:
    workflow: hypershift-aws-conformance
- as: e2e-aws-ovn-proxy-conformance
  cron: 48 23 */1,13 * *
  steps:
    cluster_profile: aws
    workflow: hypershift-aws-conformance-proxy
- as: e2e-powervs
  cron: 54 20 */5,17 * *
  steps:
    workflow: hypershift-powervs-e2e
- as: e2e-ibmcloud-iks
  cron: 51 21 */8,19 * *
  steps:
    env:
      BOM_VERSION: 4.10.26_openshift
      MANAGED_CLUSTER_TYPE: iks
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/iks.kubeconfig
      TEST_TYPE: main
      VERIFY_COMPLIANCE_OPERATOR_SCAN: "false"
    workflow: hypershift-ibmcloud-e2e
- as: e2e-ibmcloud-roks
  cron: 37 0 */10,24 * *
  steps:
    env:
      BOM_VERSION: 4.11.0_openshift
      MANAGED_CLUSTER_TYPE: openshift
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/roks.kubeconfig
      TEST_TYPE: main
      VERIFY_COMPLIANCE_OPERATOR_SCAN: "true"
    workflow: hypershift-ibmcloud-e2e
- as: e2e-aws-ovn-mce-conformance
  cron: 40 13 */11,21 * *
  steps:
    cluster_profile: aws
    workflow: hypershift-mce-aws-conformance
- as: e2e-kubevirt-conformance
  cron: 25 0 */5,16 * *
  steps:
    cluster_profile: aws
    env:
      CNV_PRERELEASE_VERSION: "4.12"
    workflow: hypershift-kubevirt-conformance
- as: e2e-kubevirt-mce-conformance
  cron: 12 7 */6,15 * *
  steps:
    cluster_profile: aws
    env:
      CNV_PRERELEASE_VERSION: "4.12"
    workflow: hypershift-mce-kubevirt-conformance
zz_generated_metadata:
  branch: release-4.12
  org: openshift
  repo: hypershift
  variant: periodics
