base_images:
  assisted-service-scripts:
    name: ocm-2.10
    namespace: edge-infrastructure
    tag: assisted-service-scripts
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: "4.15"
    namespace: ocp
    tag: hypershift-operator
  hypershift-tests:
    name: "4.15"
    namespace: ocp
    tag: hypershift-tests
  test-bin:
    name: "4.15"
    namespace: ocp
    tag: hypershift-tests
  upi-installer:
    name: "4.15"
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.15"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.15"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn
  cron: 35 15 9,21 * *
  steps:
    cluster_profile: hypershift
    workflow: hypershift-aws-e2e-metrics
- as: e2e-aws-ovn-conformance-serial
  cron: 56 3 13,15 * *
  steps:
    cluster_profile: hypershift
    env:
      TEST_SUITE: openshift/conformance/serial
    workflow: hypershift-aws-conformance
- as: e2e-aws-ovn-conformance
  cron: 50 14 7,23 * *
  steps:
    cluster_profile: hypershift
    workflow: hypershift-aws-conformance
- as: e2e-aws-ovn-proxy-conformance
  cron: 53 11 11,23 * *
  steps:
    cluster_profile: hypershift
    workflow: hypershift-aws-conformance-proxy
- as: e2e-powervs-ovn
  cron: 22 17 6,22 * *
  steps:
    cluster_profile: hypershift-powervs
    workflow: hypershift-powervs-e2e
- as: e2e-ibmcloud-ovn-iks
  cron: 45 3 5,23 * *
  steps:
    env:
      BOM_VERSION: 4.10.26_openshift
      MANAGED_CLUSTER_TYPE: iks
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/iks.kubeconfig
      TEST_TYPE: main
      VERIFY_COMPLIANCE_OPERATOR_SCAN: "false"
    workflow: hypershift-ibmcloud-e2e
- as: e2e-ibmcloud-ovn-roks
  cron: 21 11 5,22 * *
  steps:
    env:
      BOM_VERSION: 4.11.0_openshift
      MANAGED_CLUSTER_TYPE: openshift
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/roks.kubeconfig
      TEST_TYPE: main
      VERIFY_COMPLIANCE_OPERATOR_SCAN: "true"
    workflow: hypershift-ibmcloud-e2e
- as: e2e-aws-ovn-mce-conformance
  cron: 54 13 10,17 * *
  steps:
    cluster_profile: aws
    env:
      MCE_VERSION: "2.5"
    workflow: hypershift-mce-aws-conformance
- as: e2e-mce-agent-connected-ovn-ipv4-manual-conformance
  cluster: build05
  cron: 48 13 7,28 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      LVM_OPERATOR_SUB_CHANNEL: stable-4.15
      MCE_VERSION: "2.5"
    workflow: hypershift-mce-agent-manual-conformance
- as: e2e-mce-agent-connected-ovn-ipv4-metal3-conformance
  cluster: build05
  cron: 12 11 10,20 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      LVM_OPERATOR_SUB_CHANNEL: stable-4.15
      MCE_VERSION: "2.5"
    workflow: hypershift-mce-agent-metal3-conformance
- as: e2e-mce-agent-connected-ovn-dualstack-metal3-conformance
  cluster: build05
  cron: 30 21 6,24 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4v6
        NETWORK_TYPE=OVNKubernetes
        WORKER_MEMORY=14336
        VM_EXTRADISKS=true
        VM_EXTRADISKS_LIST=vda
        VM_EXTRADISKS_SIZE=500G
        NUM_EXTRA_WORKERS=3
      IP_STACK: v4v6
      LVM_OPERATOR_SUB_CHANNEL: stable-4.15
      MCE_VERSION: "2.5"
    workflow: hypershift-mce-agent-metal3-conformance
- as: e2e-mce-agent-connected-ovn-ipv4-metal3-compact-conformance
  cluster: build05
  cron: 4 16 5,15 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4
        NUM_WORKERS=0
        NUM_MASTERS=3
        MASTER_VCPU=16
        MASTER_MEMORY=32768
        NETWORK_TYPE=OVNKubernetes
        VM_EXTRADISKS=true
        VM_EXTRADISKS_LIST=vda
        VM_EXTRADISKS_SIZE=500G
        NUM_EXTRA_WORKERS=2
      LVM_OPERATOR_SUB_CHANNEL: stable-4.15
      MCE_VERSION: "2.5"
    workflow: hypershift-mce-agent-metal3-conformance
- as: e2e-kubevirt-metal-ovn
  cron: 13 19 9,26 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      HYPERSHIFT_NODE_COUNT: "2"
      LVM_OPERATOR_SUB_CHANNEL: stable-4.15
      MCE_VERSION: "2.5"
      ODF_OPERATOR_SUB_CHANNEL: stable-4.15
    workflow: hypershift-mce-kubevirt-baremetalds-conformance
- as: e2e-kubevirt-metal-ovn-mce-disconnected
  cron: 40 7 14,17 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      HYPERSHIFT_NODE_COUNT: "2"
      LVM_OPERATOR_SUB_CHANNEL: stable-4.15
      MCE_VERSION: "2.5"
      MIRROR_OLM_REMOTE_INDEX: registry.redhat.io/redhat/redhat-operator-index:v4.15
      ODF_OPERATOR_SUB_CHANNEL: stable-4.15
    workflow: hypershift-mce-kubevirt-baremetalds-disconnected-conformance
- as: e2e-kubevirt-aws-ovn-csi
  cron: 25 19 5,17 * *
  steps:
    cluster_profile: aws
    workflow: hypershift-kubevirt-csi-e2e
- as: e2e-kubevirt-aws-ovn
  cron: 28 10 8,18 * *
  steps:
    cluster_profile: aws
    env:
      COMPUTE_NODE_REPLICAS: "1"
      COMPUTE_NODE_TYPE: c5n.metal
      ENABLE_HYPERSHIFT_CERT_ROTATION_SCALE: "true"
      ENABLE_HYPERSHIFT_OPERATOR_DEFAULTING_WEBHOOK: "true"
      ETCD_STORAGE_CLASS: gp3-csi
      KUBEVIRT_CSI_INFRA: gp3-csi
    workflow: hypershift-kubevirt-e2e-aws
- as: e2e-mce-ibmz-ovn-conformance
  cron: 14 2 7,21 * *
  steps:
    cluster_profile: aws
    env:
      MCE_VERSION: "2.5"
    workflow: hypershift-mce-ibmz-conformance
- as: e2e-mce-power-ovn-conformance
  cron: 53 11 11,23 * *
  steps:
    cluster_profile: aws
    env:
      MCE_VERSION: "2.5"
    workflow: hypershift-mce-power-conformance
zz_generated_metadata:
  branch: release-4.15
  org: openshift
  repo: hypershift
  variant: periodics
