base_images:
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: '4.13'
    namespace: ocp
    tag: hypershift-operator
  hypershift-tests:
    name: '4.12'
    namespace: ocp
    tag: hypershift-tests
  upi-installer:
    name: '4.12'
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: '4.12'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.12'
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: '4.12'
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn
  steps:
    workflow: hypershift-aws-e2e-metrics
  cron: 50 10 */7,20 * *
- as: e2e-aws-ovn-conformance-serial
  steps:
    env:
      TEST_SUITE: openshift/conformance/serial
    workflow: hypershift-aws-conformance
  cron: 16 15 */9,19 * *
- as: e2e-aws-ovn-conformance
  steps:
    workflow: hypershift-aws-conformance
  cron: 42 13 */13,25 * *
- as: e2e-aws-ovn-proxy-conformance
  steps:
    cluster_profile: aws
    workflow: hypershift-aws-conformance-proxy
  cron: 30 22 */2,16 * *
- as: e2e-powervs
  steps:
    workflow: hypershift-powervs-e2e
  cron: 11 0 */14,25 * *
- as: e2e-ibmcloud-iks
  steps:
    env:
      BOM_VERSION: 4.10.26_openshift
      MANAGED_CLUSTER_TYPE: iks
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/iks.kubeconfig
      TEST_TYPE: main
      VERIFY_COMPLIANCE_OPERATOR_SCAN: 'false'
    workflow: hypershift-ibmcloud-e2e
  cron: 8 10 */6,17 * *
- as: e2e-ibmcloud-roks
  steps:
    env:
      BOM_VERSION: 4.11.0_openshift
      MANAGED_CLUSTER_TYPE: openshift
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/roks.kubeconfig
      TEST_TYPE: main
      VERIFY_COMPLIANCE_OPERATOR_SCAN: 'true'
    workflow: hypershift-ibmcloud-e2e
  cron: 14 4 */0,13 * *
- as: e2e-aws-ovn-mce-conformance
  steps:
    cluster_profile: aws
    workflow: hypershift-mce-aws-conformance
  cron: 50 18 */14,27 * *
- as: e2e-kubevirt-conformance
  steps:
    cluster_profile: aws
    env:
      CNV_PRERELEASE_VERSION: '4.12'
    workflow: hypershift-kubevirt-conformance
  cron: 10 17 */6,19 * *
- as: e2e-kubevirt-mce-conformance
  steps:
    cluster_profile: aws
    env:
      CNV_PRERELEASE_VERSION: '4.12'
    workflow: hypershift-mce-kubevirt-conformance
  cron: 48 7 */1,12 * *
zz_generated_metadata:
  branch: release-4.12
  org: openshift
  repo: hypershift
  variant: periodics
