base_images:
  upi-installer:
    name: "4.9"
    namespace: origin
    tag: upi-installer
releases:
  latest:
    candidate:
      product: okd
      stream: okd
      version: "4.9"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws
  cron: 52 20 */14 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-vsphere
  cron: 56 15 */14 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere
- as: e2e-vsphere-upi
  cron: 2 15 */14 * *
  steps:
    cluster_profile: vsphere
    workflow: upi-vsphere
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: okd-4.9
