base_images:
  assisted-image-service:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-image-service
  assisted-installer:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-installer
  assisted-installer-agent:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-installer-agent
  assisted-installer-controller:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-installer-controller
  assisted-service:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-service
  assisted-test-infra:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-test-infra
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  upi-installer:
    name: '4.12'
    namespace: origin
    tag: upi-installer
releases:
  latest:
    candidate:
      product: okd
      stream: okd
      version: '4.12'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
  cron: 39 10 */8,20 * *
- as: e2e-vsphere-ovn
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere
  cron: 0 5 */2,16 * *
- as: e2e-vsphere-upi
  steps:
    cluster_profile: vsphere
    workflow: upi-vsphere
  cron: 2 16 */6,17 * *
- as: e2e-assisted
  steps:
    cluster_profile: packet-assisted
    env:
      ASSISTED_CONFIG: |
        NUM_MASTERS=3
        NUM_WORKERS=2
        OS_IMAGES='[{"openshift_version":"4.12","cpu_architecture":"x86_64","url":"https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/37.20221225.3.0/x86_64/fedora-coreos-37.20221225.3.0-live.x86_64.iso","version": "37.20221225.3.0"}]'
    workflow: assisted-baremetal
  cron: 56 21 */14,27 * *
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: okd-4.12
