releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.12"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-sdn
  cron: 34 3 */1 * 1-5
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn
- as: e2e-aws-sdn-techpreview
  interval: 48h
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn-techpreview
- as: e2e-aws-sdn-no-capabilities
  interval: 48h
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      BASELINE_CAPABILITY_SET: None
      TEST_SKIPS: check registry.redhat.io is available and samples operator can import
        sample imagestreams
    workflow: openshift-e2e-aws-sdn
- as: e2e-aws-ovn
  cron: 26 5 */1 * 1-5
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-sdn-serial
  cron: 12 0 */1 * 1-5
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn-serial
- as: e2e-aws-ovn-serial
  cron: 54 */8 * * 1-5
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-ovn-serial
- as: e2e-aws-sdn-techpreview-serial
  interval: 48h
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn-techpreview-serial
- as: e2e-aws-sdn-multitenant
  interval: 48h
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-aws-sdn-upgrade
  cluster: build01
  cron: 48 3 */1 * 1-5
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-sdn
- as: e2e-aws-ovn-upgrade
  cluster: build01
  cron: 4 5 */1 * 1-5
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-ovn
- as: e2e-aws-cilium
  interval: 48h
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-cilium
- as: e2e-aws-sdn-imdsv2
  interval: 48h
  steps:
    cluster_profile: aws-2
    env:
      AWS_METADATA_SERVICE_AUTH: Required
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn
- as: e2e-azure-sdn
  cron: 13 8 */1 * 1-5
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-sdn
- as: e2e-azure-sdn-techpreview
  interval: 48h
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-techpreview
- as: e2e-azure-sdn-serial
  cron: 53 6 */1 * 1-5
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-sdn-serial
- as: e2e-azure-sdn-techpreview-serial
  interval: 48h
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-sdn-techpreview-serial
- as: e2e-azure-sdn-upgrade
  cron: 12 */4 * * 1-5
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure-sdn
- as: e2e-azure-ovn-upgrade
  cron: 44 0 */1 * 1-5
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure-ovn
- as: e2e-azure-cilium
  interval: 48h
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-cilium
- as: e2e-azure-ovn
  cron: 42 1 */1 * 1-5
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
    workflow: openshift-e2e-azure-ovn
- as: e2e-gcp-sdn
  cron: 52 7 */1 * 1-5
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-sdn
- as: e2e-gcp-sdn-techpreview
  interval: 48h
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-sdn-techpreview
- as: e2e-gcp-ovn
  cron: 55 1 */1 * 1-5
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: "true"
    workflow: openshift-e2e-gcp-ovn
- as: e2e-gcp-sdn-serial
  cron: 50 0 */1 * 1-5
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-sdn-serial
- as: e2e-gcp-sdn-techpreview-serial
  interval: 48h
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-sdn-techpreview-serial
- as: e2e-gcp-sdn-upgrade
  cluster: build02
  cron: 37 1 */1 * 1-5
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-gcp-sdn
- as: e2e-gcp-cilium
  interval: 48h
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-cilium
- as: e2e-aws-sdn-upgrade-rollback
  interval: 48h
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    workflow: openshift-upgrade-aws-sdn
- as: e2e-aws-upgrade-ovn-single-node
  cron: 20 2 */1 * 1-5
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-single-node
- as: e2e-azure-upgrade-ovn-single-node
  cron: 8 2 */1 * 1-5
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure-single-node
- as: e2e-network-migration
  interval: 48h
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any alerts in firing or pending state\|
        Prometheus when installed on the cluster shouldn't report any alerts in firing
        state apart from Watchdog and AlertmanagerReceiversNotConfigured
    test:
    - ref: ovn-sdn-migration
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws
- as: e2e-network-migration-rollback
  interval: 48h
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any alerts in firing or pending state\|
        Prometheus when installed on the cluster shouldn't report any alerts in firing
        state apart from Watchdog and AlertmanagerReceiversNotConfigured
    test:
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-rollback
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws
- as: e2e-aws-sdn-cgroupsv2
  cron: 37 */3 * * 1-5
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-cgroupsv2
- as: e2e-aws-sdn-crun
  cron: 46 */3 * * 1-5
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn-crun
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.12
