releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: '4.12'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.12'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-sdn
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
  cron: 7 15 */0,9 * *
- as: e2e-aws-sdn-techpreview
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
  cron: 50 5 */1,10 * *
- as: e2e-aws-ovn
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn
  cron: 5 1 */9,23 * *
- as: e2e-aws-sdn-serial
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-serial
  cron: 21 11 */4,15 * *
- as: e2e-aws-ovn-serial
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn-serial
  cron: 10 18 */8,18 * *
- as: e2e-aws-sdn-techpreview-serial
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-serial
  cron: 37 23 */6,18 * *
- as: e2e-aws-sdn-multitenant
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-multi
  cron: 24 9 */2,11 * *
- as: e2e-aws-sdn-upgrade
  cluster: build01
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-sdn
  cron: 25 5 */10,22 * *
- as: e2e-aws-ovn-upgrade
  cluster: build01
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FAIL_ON_CORE_DUMP: 'true'
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-ovn
  cron: 21 14 */13,26 * *
- as: e2e-aws-cilium
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-cilium
  cron: 18 11 */8,21 * *
- as: e2e-aws-sdn-imdsv2
  steps:
    cluster_profile: aws-2
    env:
      AWS_METADATA_SERVICE_AUTH: Required
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
  cron: 2 0 */9,18 * *
- as: e2e-azure-sdn
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn
  cron: 54 3 */0,12 * *
- as: e2e-azure-sdn-techpreview
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn
  cron: 14 3 */11,22 * *
- as: e2e-azure-sdn-serial
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn-serial
  cron: 57 8 */13,24 * *
- as: e2e-azure-sdn-techpreview-serial
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn-serial
  cron: 16 5 */9,21 * *
- as: e2e-azure-sdn-upgrade
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-sdn
  cron: 18 13 */11,20 * *
- as: e2e-azure-ovn-upgrade
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: 'true'
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-ovn
  cron: 42 14 */0,10 * *
- as: e2e-azure-cilium
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-cilium
  cron: 7 10 */3,17 * *
- as: e2e-azure-ovn
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: 'true'
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-ovn
  cron: 23 6 */10,24 * *
- as: e2e-gcp-sdn
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn
  cron: 13 21 */6,19 * *
- as: e2e-gcp-sdn-techpreview
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn
  cron: 28 16 */0,14 * *
- as: e2e-gcp-ovn
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: 'true'
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-ovn
  cron: 56 22 */2,11 * *
- as: e2e-gcp-ovn-mount-ns-hiding
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: 'true'
      MOUNT_NS_HIDING_ENABLED: 'true'
      MOUNT_NS_HIDING_LOG: '2'
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-mount-ns-hiding
  cron: 25 11 */7,20 * *
- as: e2e-gcp-sdn-serial
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn-serial
  cron: 28 10 */9,23 * *
- as: e2e-gcp-sdn-techpreview-serial
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn-serial
  cron: 24 7 */5,19 * *
- as: e2e-gcp-sdn-upgrade
  cluster: build02
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-gcp-sdn
  cron: 29 16 */3,15 * *
- as: e2e-gcp-cilium
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-cilium
  cron: 29 8 */13,23 * *
- as: e2e-aws-sdn-upgrade-rollback
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-sdn
  cron: 0 5 */7,20 * *
- as: e2e-aws-upgrade-ovn-single-node
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-single-node
  cron: 58 19 */9,18 * *
- as: e2e-aws-ovn-network-migration
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    observers:
      enable:
      - observers-resource-watch
    test:
    - ref: ovn-sdn-migration-feature-migration-config-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-config-egress-ip
    - ref: ovn-sdn-migration-feature-migration-config-multicast
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-feature-migration-validate-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-validate-egress-ip
    - ref: ovn-sdn-migration-feature-migration-validate-multicast
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws-sdn
  cron: 16 13 */6,19 * *
- as: e2e-network-migration-rollback
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    observers:
      enable:
      - observers-resource-watch
    test:
    - ref: ovn-sdn-migration-feature-migration-config-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-config-egress-ip
    - ref: ovn-sdn-migration-feature-migration-config-multicast
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-rollback
    - ref: ovn-sdn-migration-feature-migration-validate-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-validate-egress-ip
    - ref: ovn-sdn-migration-feature-migration-validate-multicast
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws-sdn
  cron: 34 19 */5,16 * *
- as: e2e-aws-sdn-cgroupsv2
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-cgroupsv2
  cron: 11 6 */14,28 * *
- as: e2e-aws-sdn-crun
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-crun
  cron: 34 6 */6,16 * *
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.12
