releases:
  initial:
    prerelease:
      product: okd
      version_bounds:
        lower: 4.11.0
        upper: 4.999.0
  latest:
    candidate:
      product: okd
      stream: okd-scos
      version: '4.12'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
  cron: 53 19 */6,15 * *
- as: e2e-aws-ovn-upgrade
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
  cron: 48 14 */14,28 * *
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: okd-scos-4.12
