releases:
  initial:
    candidate:
      product: okd
      stream: okd
      version: '4.11'
  latest:
    candidate:
      product: okd
      stream: okd
      version: '4.12'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn-upgrade
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-upgrade-aws
  cron: 1 14 */1,10 * *
- as: e2e-gcp-ovn-upgrade
  steps:
    cluster_profile: gcp
    workflow: openshift-upgrade-gcp
  cron: 38 23 */7,19 * *
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: okd-4.12-upgrade-from-okd-4.11
