releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.12"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-sdn
  cron: 36 21 */4,15 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
- as: e2e-aws-sdn-techpreview
  cron: 12 13 */9,21 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
- as: e2e-aws-ovn
  cron: 55 12 */9,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-sdn-serial
  cron: 57 12 */2,15 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-serial
- as: e2e-aws-ovn-serial
  cron: 51 20 */6,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn-serial
- as: e2e-aws-sdn-techpreview-serial
  cron: 39 4 */13,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-serial
- as: e2e-aws-sdn-multitenant
  cron: 22 6 */12,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-aws-sdn-upgrade
  cluster: build01
  cron: 24 14 */4,13 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-sdn
- as: e2e-aws-ovn-upgrade
  cluster: build01
  cron: 53 7 */10,24 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-ovn
- as: e2e-aws-cilium
  cron: 4 15 */5,15 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-cilium
- as: e2e-aws-sdn-imdsv2
  cron: 10 14 */11,23 * *
  steps:
    cluster_profile: aws-2
    env:
      AWS_METADATA_SERVICE_AUTH: Required
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
- as: e2e-azure-sdn
  cron: 38 20 */11,25 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn
- as: e2e-azure-sdn-techpreview
  cron: 59 2 */1,12 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn
- as: e2e-azure-sdn-serial
  cron: 17 20 */1,11 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn-serial
- as: e2e-azure-sdn-techpreview-serial
  cron: 34 15 */8,19 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn-serial
- as: e2e-azure-sdn-upgrade
  cron: 0 11 */3,14 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-sdn
- as: e2e-azure-ovn-upgrade
  cron: 15 10 */6,16 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-ovn
- as: e2e-azure-cilium
  cron: 0 3 */4,15 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-cilium
- as: e2e-azure-ovn
  cron: 31 1 */8,22 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-ovn
- as: e2e-gcp-sdn
  cron: 55 10 */9,19 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn
- as: e2e-gcp-sdn-techpreview
  cron: 28 2 */1,14 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn
- as: e2e-gcp-ovn
  cron: 8 8 */9,23 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: "true"
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-ovn
- as: e2e-gcp-ovn-mount-ns-hiding
  cron: 14 2 */13,26 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: "true"
      MOUNT_NS_HIDING_ENABLED: "true"
      MOUNT_NS_HIDING_LOG: "2"
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-mount-ns-hiding
- as: e2e-gcp-sdn-serial
  cron: 14 1 */1,10 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn-serial
- as: e2e-gcp-sdn-techpreview-serial
  cron: 49 15 */7,18 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn-serial
- as: e2e-gcp-sdn-upgrade
  cluster: build02
  cron: 2 11 */13,22 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-gcp-sdn
- as: e2e-gcp-cilium
  cron: 43 10 */11,21 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-cilium
- as: e2e-aws-sdn-upgrade-rollback
  cron: 26 3 */8,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-sdn
- as: e2e-aws-upgrade-ovn-single-node
  cron: 52 15 */14,27 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-single-node
- as: e2e-aws-ovn-network-migration
  cron: 43 21 */8,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    observers:
      enable:
      - observers-resource-watch
    test:
    - ref: ovn-sdn-migration-feature-migration-config-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-config-egress-ip
    - ref: ovn-sdn-migration-feature-migration-config-multicast
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-feature-migration-validate-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-validate-egress-ip
    - ref: ovn-sdn-migration-feature-migration-validate-multicast
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws-sdn
- as: e2e-network-migration-rollback
  cron: 17 7 */5,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    observers:
      enable:
      - observers-resource-watch
    test:
    - ref: ovn-sdn-migration-feature-migration-config-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-config-egress-ip
    - ref: ovn-sdn-migration-feature-migration-config-multicast
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-rollback
    - ref: ovn-sdn-migration-feature-migration-validate-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-validate-egress-ip
    - ref: ovn-sdn-migration-feature-migration-validate-multicast
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws-sdn
- as: e2e-aws-sdn-cgroupsv2
  cron: 26 10 */10,23 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-cgroupsv2
- as: e2e-aws-sdn-crun
  cron: 51 19 */3,17 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-crun
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.12
