approve:
- commandHelpLink: https://go.k8s.io/bot-commands
  repos:
  - openshift-priv/cluster-node-tuning-operator
  require_self_approval: false
lgtm:
- repos:
  - openshift-priv/cluster-node-tuning-operator
  review_acts_as_lgtm: true
