base_images:
  cli:
    name: '4.12'
    namespace: ocp
    tag: cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: '4.12'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: cspi-qe-slack-poc-pass
  remote_api: true
  steps:
    test:
    - as: report-passing
      commands: |
        echo "dummy passing test"
      from: cli
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
  cron: 20 6 */2,14 * *
- as: cspi-qe-slack-poc-fail
  remote_api: true
  steps:
    test:
    - as: report-faling
      commands: |
        echo "dummy failing test"
        exit 1
      from: cli
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
  cron: 54 9 */3,17 * *
zz_generated_metadata:
  branch: main
  org: rhpit
  repo: interop-tests
  variant: slack-poc
