base_images:
  openstack-cinder-csi-driver-operator-test:
    name: "4.9"
    namespace: ocp
    tag: openstack-cinder-csi-driver-operator-test
  openstack-installer:
    name: "4.9"
    namespace: ocp
    tag: openstack-installer
  openstack-tests:
    name: "4.9"
    namespace: ocp
    tag: openstack-tests
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.9"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.9"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-openstack-fips
  cron: 15 3 */14 * *
  steps:
    cluster_profile: openstack-vexxhost
    env:
      FIPS_ENABLED: "true"
      TEST_SUITE: experimental/reliability/minimal
    pre:
    - chain: ipi-openstack-pre
    - ref: fips-check
    workflow: openshift-e2e-openstack-ipi
- as: e2e-openstack-proxy
  cron: 33 13 */14 * *
  steps:
    cluster_profile: openstack-vh-mecha-central
    workflow: openshift-e2e-openstack-proxy
- as: e2e-openstack-nfv-intel
  cron: 49 20 */14 * *
  steps:
    cluster_profile: openstack-nfv
    workflow: openshift-e2e-openstack-nfv
- as: e2e-openstack-nfv-mellanox
  cron: 7 15 */14 * *
  steps:
    cluster_profile: openstack-nfv
    env:
      ADDITIONAL_WORKERS_NETWORKS: mellanox-dpdk
      OPENSTACK_DPDK_NETWORK: mellanox-dpdk
      OPENSTACK_SRIOV_NETWORK: mellanox-sriov
    workflow: openshift-e2e-openstack-nfv
- as: e2e-openstack-az
  cron: 17 0 */14 * *
  steps:
    cluster_profile: openstack-vh-mecha-az0
    env:
      TEST_SKIPS: In-tree Volumes
      ZONES_COUNT: "1"
    workflow: openshift-e2e-openstack-proxy
- as: e2e-openstack-csi-cinder
  cron: 53 22 */14 * *
  steps:
    cluster_profile: openstack-vh-mecha-central
    workflow: openshift-e2e-openstack-csi-cinder
- as: e2e-openstack-parallel
  cron: 45 3 */14 * *
  steps:
    cluster_profile: openstack-vexxhost
    env:
      TEST_SUITE: openshift/conformance/parallel
    workflow: openshift-e2e-openstack-ipi
- as: e2e-openstack-serial
  cron: 0 14 */14 * *
  steps:
    cluster_profile: openstack-vexxhost
    env:
      TEST_SUITE: openshift/conformance/serial
    workflow: openshift-e2e-openstack-ipi
- as: e2e-openstack-ovn
  cron: 50 18 */14 * *
  steps:
    cluster_profile: openstack-vexxhost
    workflow: openshift-e2e-openstack-ovn
- as: e2e-openstack-kuryr
  cron: 41 20 */14 * *
  steps:
    cluster_profile: openstack-kuryr
    env:
      NETWORK_TYPE: Kuryr
      TEST_SKIPS: NodePort \| session affinity \| Services should serve a basic endpoint
        from pods \| Kubectl client Guestbook application should create and stop a
        working application \| Pods should delete a collection of pods \| Services
        should serve multiport endpoints \| Services should be able to change the
        type from ExternalName to ClusterIP
      TEST_SUITE: kubernetes/conformance
    workflow: openshift-e2e-openstack-ipi
zz_generated_metadata:
  branch: main
  org: shiftstack
  repo: shiftstack-ci
  variant: periodic-4.9
